services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: justicia-rrhh-backend
    volumes:
      - ./rrhh-backend:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9080:80" # Cambiado de 8080 a 9080
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.6
    container_name: justicia-db
    ports:
      - "3390:3306" # Cambiado de 3306 a 3308
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9081:8080" # Cambiado de 8081 a 9081
    depends_on:
      - db


volumes:
  db_data:

